server {
  server_name app.campuslab.app;
  listen 443 ssl;

  root /home/deploy/campus-lab/pwa/dist;
  index index.html;

  add_header X-Frame-Options DENY;
  add_header X-Content-Type-Options nosniff;
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

  location /service-worker.js {
    add_header Cache-Control "no-cache, no-store, must-revalidate";
    add_header Pragma "no-cache";
    expires 0;
    try_files $uri $uri/ =404;
  }

  location /manifest.json {
    add_header Cache-Control "no-cache";
    try_files $uri $uri/ =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
    add_header Cache-Control "no-cache";
  }

  location /assets/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}
